---
- name: Initialize VM
  connection: local 
  hosts: all
  remote_user: vagrant
  become: yes
  become_user: root

  roles:
  - base

- name: Install Server environment
  connection: local
  hosts: all
  become: yes

  roles:
  - webserver
