---
- name: Install Centos packages
  include_tasks: centos-packages.yml
  when: (ansible_distribution == "CentosOS" and ansible_distribution_major_version == "7") or
        (ansible_distribution == "CentosOS" and ansible_distribution_major_version == "8")
  tags:
    - initCentos

- name: Start Firewall
  include_tasks: firewall.yml

- name: Add Users
  include_tasks: users.yml