---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Prometheus
  become: true
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Restart Node Exporter
  become: true
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes